
@hostname = http://localhost
@port = 3001
@host = {{hostname}}:{{port}}
@contentType = application/json
@persons = /api/persons
@id = 620c44e60b0c3cd0dd3539bf

###

GET {{host}}{{persons}} HTTP/1.1

###

GET {{host}}{{persons}}/{{id}} HTTP/1.1

###

POST {{host}}{{persons}} HTTP/1.1
Content-Type: {{contentType}}

{
  "name": "Jesus",
  "number": "234-12313"
}

###

DELETE {{host}}{{persons}}/{{id}} HTTP/1.1

###

PUT {{host}}{{persons}}/{{id}} HTTP/1.1
Content-Type: {{contentType}}

{
  "name": "Jesus",
  "number": "2131"
}
###